name: my pipeline

"on":
    workflow_dispatch:
        inputs:  
            Files:
                description: '[1] Batch, [2] Database, [3] Config'
                required: true
                default: '1'
