name: my pipeline

"on":
    workflow_dispatch:
        inputs:  
            Files:
                description: '[1] batch, [2] database'
                required: true
                default: '1'

jobs:
  test: testing the stage
  
    runs-on: ubuntu-latest
    steps:
      - name: Set Files
        run: |
          if [[ "${{ github.event.inputs.Files }}" == "1" ]]; then
              echo "::set-output name=FilesString::batch"
          fi
          if [[ "${{ github.event.inputs.device }}" == "2" ]]; then
              echo "::set-output name=FilesString::Datbase"
          fi
